# Site settings
title: DungBeetleBASH
description: Makers of Farty Turd for Android and other stuff.
email: dungbeetlebash@gmail.com
baseurl: 
url: "https://dungbeetlebash.github.io" # the base hostname & protocol for your site
#favicon
favicon: /favicon.png

#feed
#feedburner_username: maangalabs
#twitter
#twitter_username: 
github_username:  DungBeetleBASH

#linkedin
#linkedin_username: 

#google analytics
#google_analytics_id : 
#gplus
gplus_username: 108436493437282884898

#fb_username
#fb_username: 

#permalink /blog/2014/11/11/this-is-a-sample-post
permalink: /blog/:year/:month/:day/:title
# Build settings
markdown: kramdown

#Disqus configuration
#disqus_short_name: 
#disqus_show_comment_count: true

#Can be used for multiple author blogs ! Add name to post For more visit the sample
authors:
  Pappa:
    display_name: Pappa
    email: dungbeetlebash@gmail.com
#    fb: 
#    linkedin: 
#    twitter: 
    github: DungBeetleBASH
