# Site Info
title: DungBeetleBASH
tagline: 'Can\'t decide if personal or professional'
description: 'Somewhere to mull over my programming experiments.'
baseurl: ""
url: https://dungbeetlebash.github.io
logo: '/public/img/refactoring-hat.png'
favicon: /favicon.ico

# Site configurations
gems:
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss    
paginate: 5
paginate_path: '/page:num'
permalink: pretty

version: 1.0.0

# About/contact
author:
  name: Pappa
  description: Code monkey.
  gravatar: be82c4e5dd6079e8f68b97599cb131bb # md5 hash of your email address
  contact:
    #linkedin:  <hide>
    github:    https://github.com/DungBeetleBASH
    # facebook:  <hide>
    # twitter:   <hide>
    # weibo:     <hide>
    # email:     <hide>

# Navigation (2nd level links supported)
nav:
  Home:           
    - '/'
    - { Categories: '/categories/' }
    - { Tags: '/tags/' }
  About:          
    - '/about/'
  Github Project: 
    - 'https://github.com/DungBeetleBASH'

# Where are tags and categories displayed
tag_page: '/tags/'
category_page: '/categories/'

hero:
  image: /public/img/two-hats.png
  caption: Never wear two hats at the same time. It's silly.

# Puglins
mathjax: true # whether support mathjax
# google_analytics_token: 'UA-00000000-1' # leave blank if you don't want google analytics
# disqus_short_name: 'your_short_name' # leave blank if you don't want disqus

